"""Compute all reported statistics from data/*.csv. Nothing in the paper is a number
that this script cannot reproduce.

Usage: python code/analyze.py  [-> writes data/RESULTS.md and prints a summary]
"""

import csv
import json
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"


def load(name):
    return list(csv.DictReader(open(DATA / name, encoding="utf-8")))


def cohens_kappa(pairs):
    """Unweighted Cohen's kappa over (rater1, rater2) categorical pairs."""
    n = len(pairs)
    if n == 0:
        return float("nan")
    cats = sorted({c for p in pairs for c in p})
    obs = sum(1 for a, b in pairs if a == b) / n
    m1 = Counter(a for a, _ in pairs)
    m2 = Counter(b for _, b in pairs)
    exp = sum((m1[c] / n) * (m2[c] / n) for c in cats)
    return (obs - exp) / (1 - exp) if exp != 1 else float("nan")


def main():
    out = []
    w = out.append

    cand = {r["arxiv_id"]: r for r in load("candidates.csv")}
    meta = json.loads((DATA / "expert-identified-meta.json").read_text(encoding="utf-8"))
    for pid, m in meta.items():
        cand.setdefault(pid, {**m, "first_submitted": "", "primary_category": "",
                              "categories": "", "matched_queries": "expert-identified"})
    l1 = load("screening-decisions.csv")
    fin = load("screening-final.csv")
    manifest = (DATA / "HARVEST_MANIFEST.md").read_text(encoding="utf-8")

    w("# Results (auto-generated by code/analyze.py)\n")

    # --- PRISMA-style flow ---
    n_harvest = len(cand) - len(meta)
    n_expert = len(meta)
    n_window = sum(1 for r in cand.values() if r.get("first_submitted", "") >= "2024-01-01")
    n_screened = len(fin)
    inc = [r for r in fin if r["final_decision"] == "include"]
    exc = [r for r in fin if r["final_decision"] != "include"]
    w("## PRISMA-style flow\n")
    w(f"- Records identified by database search (arXiv API, 42 queries): **{n_harvest}**")
    w(f"- Records identified by other methods (expert-identified): **{n_expert}**")
    w(f"- Records in codable window (first submitted >= 2024-01-01): **{n_window}**")
    w(f"- Records screened (window + expert-identified): **{n_screened}**")
    w(f"- Records excluded: **{len(exc)}**")
    w(f"- **Papers included in the corpus: {len(inc)}**\n")

    # --- Layer-1 inter-rater reliability ---
    pairs = [(r["passA_decision"], r["passB_decision"]) for r in l1]
    raw = sum(1 for a, b in pairs if a == b) / len(pairs)
    k_all = cohens_kappa(pairs)
    # binary collapse: borderline counted as its own category above; here include vs not
    bin_pairs = [("include" if a == "include" else "not", "include" if b == "include" else "not")
                 for a, b in pairs]
    k_bin = cohens_kappa(bin_pairs)
    w("## Layer 1 — dual-pass screening reliability (RQ4)\n")
    w(f"- Papers dual-screened: **{len(pairs)}** (Pass A: Claude Fable 5, criteria-first prompt;")
    w("  Pass B: Claude Opus 5, question-first prompt)")
    w(f"- Raw agreement (3-way: include/exclude/borderline): **{raw:.3f}**")
    w(f"- Cohen's kappa (3-way): **{k_all:.3f}**")
    w(f"- Cohen's kappa (binary include vs not): **{k_bin:.3f}**")
    w(f"- Decisions requiring adjudication (disagreement or any borderline): "
      f"**{sum(1 for r in l1 if r['agreement'] == 'needs_adjudication')}** "
      f"({sum(1 for r in l1 if r['agreement'] == 'needs_adjudication') / len(l1):.1%})")
    dis = Counter((a, b) for a, b in pairs if not (a == b and a != "borderline"))
    w("\nDisagreement structure (Pass A, Pass B):\n")
    w("| Pass A | Pass B | n |\n|---|---|---|")
    for (a, b), n in dis.most_common():
        w(f"| {a} | {b} | {n} |")
    w("")

    # --- Layer 2 boundary rules ---
    w("## Layer 2 — amended criteria (amendment A1)\n")
    w(f"- Reversals of unanimous Layer-1 includes: "
      f"**{sum(1 for r in fin if r['reverses_unanimous_include'] == '1')}**\n")
    w("Inclusion reasons:\n")
    w("| code | n |\n|---|---|")
    for c, n in Counter(r["final_reason"] for r in inc).most_common():
        w(f"| {c} | {n} |")
    w("\nExclusion reasons:\n")
    w("| code | n |\n|---|---|")
    for c, n in Counter(r["final_reason"] for r in exc).most_common():
        w(f"| {c} | {n} |")
    w("\nBoundary rule invoked (all decisions):\n")
    w("| rule | included | excluded |\n|---|---|---|")
    ri = Counter(r["rule_applied"] for r in inc)
    re_ = Counter(r["rule_applied"] for r in exc)
    for rule in sorted(set(ri) | set(re_)):
        w(f"| {rule} | {ri.get(rule, 0)} | {re_.get(rule, 0)} |")
    w("")

    # --- Corpus over time (RQ3) ---
    w("## RQ3 — corpus growth\n")
    def quarter(d):
        return f"{d[:4]}-Q{(int(d[5:7]) - 1) // 3 + 1}" if len(d) >= 7 else "unknown"
    inc_dates = [cand[r["arxiv_id"]].get("first_submitted", "") for r in inc]
    w("Included papers by quarter of first submission:\n")
    w("| quarter | n |\n|---|---|")
    for q, n in sorted(Counter(quarter(d) for d in inc_dates if d).items()):
        w(f"| {q} | {n} |")
    w("\nAll harvested candidates by year (trend context, includes pre-2024):\n")
    w("| year | n |\n|---|---|")
    for y, n in sorted(Counter(r.get("first_submitted", "")[:4]
                               for r in cand.values() if r.get("first_submitted")).items()):
        w(f"| {y} | {n} |")
    w("")

    # --- Category distribution ---
    w("## Included corpus — arXiv primary category\n")
    w("| category | n |\n|---|---|")
    for c, n in Counter(cand[r["arxiv_id"]].get("primary_category", "?")
                        for r in inc).most_common(12):
        w(f"| {c} | {n} |")
    w("")

    # --- Coding results (if present) ---
    coded_path = DATA / "coded-corpus.csv"
    if coded_path.exists():
        coded = load("coded-corpus.csv")
        w(f"## Coded corpus ({len(coded)} papers)\n")
        multi = {"D3", "D5", "D6"}
        for dim in ["D1", "D2", "D3", "D4", "D5", "D6", "D7_code", "D7_data", "D8", "D9"]:
            c = Counter()
            for r in coded:
                v = r.get(dim, "")
                for part in (v.split(";") if dim in multi else [v]):
                    if part.strip():
                        c[part.strip()] += 1
            w(f"\n### {dim}\n")
            w("| code | n |\n|---|---|")
            for k, n in c.most_common():
                w(f"| {k} | {n} |")
        # RQ2 auditability gap (prespecified operationalization)
        weak, audited = [], []
        for r in coded:
            d5 = {x.strip() for x in r.get("D5", "").split(";") if x.strip()}
            d6 = {x.strip() for x in r.get("D6", "").split(";") if x.strip()}
            strong_claim = r.get("D8") in {"DISCOVERY", "CAPABILITY"}
            if strong_claim and d5 <= {"NONE", "LLM_JUDGE"} and r.get("D7_code") != "YES":
                weak.append(r["arxiv_id"])
            if d5 & {"HUMAN_EXPERT", "HELD_OUT_TRANSFER", "REAL_WORLD"} or \
               d6 & {"REPRO_ARTIFACTS", "FORMAL_VERIF"}:
                audited.append(r["arxiv_id"])
        w("\n## RQ2 — auditability gap (prespecified)\n")
        w(f"- Strong-claim / weak-verification papers: **{len(weak)}** "
          f"({len(weak) / len(coded):.1%} of coded corpus)")
        w(f"- Papers with at least one strong verification mechanism: **{len(audited)}** "
          f"({len(audited) / len(coded):.1%})")
        (DATA / "auditability-gap-papers.txt").write_text("\n".join(weak), encoding="utf-8")

    text = "\n".join(out) + "\n"
    (DATA / "RESULTS.md").write_text(text, encoding="utf-8")
    write_macros(cand, l1, fin, inc)
    print(text[:3000])
    print("...\n[full output in data/RESULTS.md]")


def write_macros(cand, l1, fin, inc):
    """Emit paper/numbers.tex so no number in the paper is hand-transcribed."""
    m = {}
    coded_path = DATA / "coded-corpus.csv"
    art_path = DATA / "artifact-verification.csv"

    def thousands(n):
        return f"{n:,}".replace(",", "{,}")  # LaTeX-safe thousands separator

    m["nHarvest"] = thousands(len(cand) - 2)
    m["nExpert"] = 2
    m["nScreened"] = thousands(len(fin))
    m["nCorpus"] = len(inc)
    m["nExcluded"] = len(fin) - len(inc)

    pairs = [(r["passA_decision"], r["passB_decision"]) for r in l1]
    m["kappaThree"] = f"{cohens_kappa(pairs):.2f}"
    m["kappaBinary"] = f"{cohens_kappa([('include' if a == 'include' else 'n', 'include' if b == 'include' else 'n') for a, b in pairs]):.2f}"
    m["rawAgree"] = f"{sum(1 for a, b in pairs if a == b) / len(pairs):.1%}".replace("%", "\\%")
    nadj = sum(1 for r in l1 if r["agreement"] == "needs_adjudication")
    m["nAdjudicate"] = nadj
    m["nAgreedLayerOne"] = len(l1) - nadj
    m["pctAdjudicate"] = f"{nadj / len(l1):.1%}".replace("%", "\\%")
    m["nReversals"] = sum(1 for r in fin if r["reverses_unanimous_include"] == "1")

    if (DATA / "screening-consistency.csv").exists():
        cons = load("screening-consistency.csv")
        m["consAgree"] = f"{sum(int(r['agree']) for r in cons) / len(cons):.1%}".replace("%", "\\%")
        m["nCons"] = len(cons)

    if coded_path.exists():
        coded = load("coded-corpus.csv")
        n = len(coded)
        m["nCoded"] = n

        def pct(k):
            return f"{k / n:.0%}".replace("%", "\\%")

        d1 = Counter(r["D1"] for r in coded)
        for k, v in d1.items():
            m["n" + k.title().replace("_", "")] = v
        d2 = Counter(r["D2"] for r in coded)
        m["nClosedLoop"] = d2.get("L3_CLOSED_LOOP", 0)
        m["nFullAuto"] = d2.get("L4_FULL", 0)
        m["nSystemsCoded"] = sum(v for k, v in d2.items() if k not in ("NA", "UNCLEAR"))

        def multi(dim, code):
            return sum(1 for r in coded if code in r[dim].split(";"))

        m["nAuditNone"] = multi("D6", "NONE")
        m["pctAuditNone"] = pct(m["nAuditNone"])
        m["nBenchMetric"] = multi("D5", "BENCHMARK_METRIC")
        m["pctBenchMetric"] = pct(m["nBenchMetric"])
        m["nNeedsFulltext"] = sum(1 for r in coded if r["needs_fulltext"] == "1")
        # prespecified auditability-gap operationalization (protocol codebook)
        weak = [r for r in coded
                if r["D8"] in ("DISCOVERY", "CAPABILITY")
                and set(r["D5"].split(";")) <= {"NONE", "LLM_JUDGE"}
                and r["D7_code"] != "YES"]
        m["nWeakStrong"] = len(weak)
        m["pctWeakStrong"] = pct(len(weak))
        m["nHeldOut"] = multi("D5", "HELD_OUT_TRANSFER")
        m["pctHeldOut"] = pct(m["nHeldOut"])
        m["nRealWorld"] = multi("D5", "REAL_WORLD")
        m["pctRealWorld"] = pct(m["nRealWorld"])
        m["nHumanExpert"] = multi("D5", "HUMAN_EXPERT")
        m["pctHumanExpert"] = pct(m["nHumanExpert"])
        m["nLLMJudge"] = multi("D5", "LLM_JUDGE")
        m["pctLLMJudge"] = pct(m["nLLMJudge"])
        m["nNoEval"] = multi("D5", "NONE")
        m["pctNoEval"] = pct(m["nNoEval"])
        m["nTraces"] = multi("D6", "TRACES")
        m["nProvenance"] = multi("D6", "PROVENANCE")
        m["nFormalVerif"] = multi("D6", "FORMAL_VERIF")

        d9 = Counter(r["D9"] for r in coded)
        unspec = d9.get("NONE_CLAIMED", 0) + d9.get("UNSPECIFIED", 0)
        m["nHumanUnspec"] = unspec
        m["pctHumanUnspec"] = pct(unspec)

        d8 = Counter(r["D8"] for r in coded)
        m["nDiscovery"] = d8.get("DISCOVERY", 0)
        m["nCapability"] = d8.get("CAPABILITY", 0)
        m["nMethodClaim"] = d8.get("METHOD", 0)
        m["nConceptual"] = d8.get("CONCEPTUAL", 0)

        disc = [r for r in coded if r["D8"] == "DISCOVERY"]
        if disc:
            m["nDiscNoAudit"] = sum(1 for r in disc if r["D6"] == "NONE")
            m["pctDiscNoAudit"] = f"{m['nDiscNoAudit'] / len(disc):.0%}".replace("%", "\\%")
            m["nDiscRealWorld"] = sum(1 for r in disc if "REAL_WORLD" in r["D5"].split(";"))
            m["pctDiscRealWorld"] = f"{m['nDiscRealWorld'] / len(disc):.0%}".replace("%", "\\%")

        # growth
        def quarter(d):
            return f"{d[:4]}Q{(int(d[5:7]) - 1) // 3 + 1}" if len(d) >= 7 else None
        qc = Counter(q for q in (quarter(r["first_submitted"]) for r in coded) if q)
        ks = sorted(qc)
        m["firstQ"] = ks[0].replace("Q", "\\,Q")
        m["firstQn"] = qc[ks[0]]
        m["peakQ"] = ks[-2].replace("Q", "\\,Q")
        m["peakQn"] = qc[ks[-2]]
        m["growthFactor"] = f"{qc[ks[-2]] / qc[ks[0]]:.0f}"
        m["partialQ"] = ks[-1].replace("Q", "\\,Q")
        m["partialQn"] = qc[ks[-1]]

        # artifact verification (full text, mechanical)
        if art_path.exists():
            art = {r["arxiv_id"]: r for r in load("artifact-verification.csv")}
            ok = [r for r in coded if art.get(r["arxiv_id"], {}).get("status") == "ok"]
            if ok:
                m["nArtChecked"] = len(ok)
                repo = sum(1 for r in ok if art[r["arxiv_id"]]["has_repo"] == "1")
                m["nRepo"] = repo
                m["pctRepo"] = f"{repo / len(ok):.0%}".replace("%", "\\%")
                abs_yes = sum(1 for r in ok if r["D7_code"] == "YES")
                m["pctRepoAbstract"] = f"{abs_yes / len(ok):.0%}".replace("%", "\\%")
                dok = [r for r in ok if r["D8"] == "DISCOVERY"]
                if dok:
                    dr = sum(1 for r in dok if art[r["arxiv_id"]]["has_repo"] == "1")
                    m["nDiscChecked"] = len(dok)
                    m["nDiscRepo"] = dr
                    m["pctDiscRepo"] = f"{dr / len(dok):.0%}".replace("%", "\\%")

    lines = ["% Auto-generated by code/analyze.py — do not edit by hand.",
             "% Every number in the paper is defined here and derived from data/."]
    for k, v in m.items():
        lines.append(f"\\newcommand{{\\{k}}}{{{v}}}")
    (ROOT / "paper" / "numbers.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\n[wrote paper/numbers.tex with {len(m)} macros]")


if __name__ == "__main__":
    main()
