"""Generate paper/references.bib from live arXiv metadata.

Citation keys map to arXiv IDs here; titles, authors, and years are fetched from the API
rather than typed. A citation in this paper therefore cannot be fabricated: if an ID does
not resolve, the script fails loudly and no entry is written.

Usage: python code/gen_bib.py
"""

import re
import sys
import time
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NS = {"atom": "http://www.w3.org/2005/Atom"}

CITES = {
    "lu2024aiscientist": "2408.06292",
    "yamada2025aiscientistv2": "2504.08066",
    "huang2026nais": "2607.11084",
    "huang2026grounded": "2607.02329",
    "zheng2026scion": "2607.03863",
    "takahara2026hep": "2607.09195",
    "wang2026firstresearch": "2607.05682",
    "li2026calibration": "2606.31273",
    "bowkis2026automated": "2605.06390",
    "gyevnar2026ddos": "2607.10712",
    "ning2026autoresearch": "2607.17100",
    "ma2026sage": "2606.31478",
    "shi2026sdabench": "2607.11079",
    "chen2026causalgame": "2607.04293",
    "brzozowski2026ghost": "2606.02184",
    "ying2026stratigraphy": "2605.28102",
    "ramos2024llmchem": "2407.01603",
}


def fetch(arxiv_id):
    url = "http://export.arxiv.org/api/query?" + urllib.parse.urlencode(
        {"id_list": arxiv_id, "max_results": 1})
    with urllib.request.urlopen(url, timeout=60) as r:
        root = ET.fromstring(r.read())
    e = root.find("atom:entry", NS)
    if e is None:
        raise SystemExit(f"FATAL: arXiv id {arxiv_id} did not resolve")
    title = " ".join(e.findtext("atom:title", "", NS).split())
    if not title:
        raise SystemExit(f"FATAL: arXiv id {arxiv_id} returned no title")
    authors = [a.findtext("atom:name", "", NS) for a in e.findall("atom:author", NS)]
    year = e.findtext("atom:published", "", NS)[:4]
    prim = e.find("{http://arxiv.org/schemas/atom}primary_category")
    cat = prim.get("term") if prim is not None else "cs.AI"
    return title, authors, year, cat


def escape(s):
    return (s.replace("&", r"\&").replace("%", r"\%").replace("_", r"\_")
             .replace("#", r"\#"))


def main():
    out = ["% Generated by code/gen_bib.py from live arXiv metadata — do not edit by hand.",
           "% Verify with: python code/verify_bib.py", ""]
    for key, aid in CITES.items():
        title, authors, year, cat = fetch(aid)
        # protect capitalisation of acronyms and proper nouns
        t = re.sub(r"\b([A-Z][A-Za-z0-9\-]*[A-Z0-9][A-Za-z0-9\-]*)\b", r"{\1}", escape(title))
        out.append(f"@article{{{key},")
        out.append(f"  title        = {{{t}}},")
        out.append(f"  author       = {{{' and '.join(escape(a) for a in authors)}}},")
        out.append(f"  journal      = {{arXiv preprint arXiv:{aid}}},")
        out.append(f"  year         = {{{year}}},")
        out.append(f"  eprint       = {{{aid}}},")
        out.append("  archivePrefix= {arXiv},")
        out.append(f"  primaryClass = {{{cat}}}")
        out.append("}\n")
        print(f"  {key}: {title[:70]}")
        time.sleep(3)
    (ROOT / "paper" / "references.bib").write_text("\n".join(out), encoding="utf-8")
    print(f"\nwrote paper/references.bib ({len(CITES)} entries)")


if __name__ == "__main__":
    main()
